package IfJava;

import javax.swing.JOptionPane;

/*
public class MainJOP {

    public static void main(String[] args) {
        String salarioInicialMje = JOptionPane.showInputDialog("Ingrese su salario sin ajuste: ");
        String porcentajeAumentoMje = JOptionPane.showInputDialog("Ingrese el aumento del salario: ");
        float salarioInicial = Float.parseFloat(salarioInicialMje);
        Float porcentajeAumento = Float.parseFloat(porcentajeAumentoMje);


        EjercicioIf pruebaJOP = new EjercicioIf(salarioInicial, porcentajeAumento, 0);
        float salarioFinal = pruebaJOP.calcularSalario();
        JOptionPane.showMessageDialog(null," el salario con aumento es igual a:"+salarioFinal);
    }


}
*/
